# Project version
version=0.0.2-SNAPSHOT

# Library versions
kotlin_version=2.1.21
junit_jupiter_version=5.8.2
commons_codec_version=1.16.0
commons_collections4_version=4.4
commons_lang3_version=3.13.0
guava_version=31.0.1-jre
okhttp_version=4.12.0
fastjson2_version=2.0.42
jackson_version=2.15.3
slf4j_version=2.0.6

# Build properties
project_build_sourceEncoding=UTF-8
maven_compiler_source=11
maven_compiler_target=11